/**
 * MCP (Model Context Protocol) client integration.
 *
 * Connects to MCP servers over SSE or stdio and exposes their tools via {@link ToolRegistry}.
 */
export {
  MCP_PROTOCOL_VERSION,
  MCPClient,
  MCPProtocolError,
  MCPRegistry,
  MCPRegistryConnectError,
  MCPTool,
  MCPToolError,
  MCPToolProvider,
  RequestIdGenerator,
  SseMCPTransport,
  SseParser,
  StdioMCPTransport,
  assertJsonRpcSuccess,
  buildNotification,
  buildRequest,
  createMCPTool,
  normalizeMcpInputSchema,
  extractTextContent,
  isJsonRpcNotification,
  isJsonRpcResponse,
  normalizeToolCallResult,
  parseInboundJsonRpcMessage,
  parseJsonRpcMessage,
  resolveTransportResult,
  type CreateMCPToolOptions,
  type JsonRpcError,
  type JsonRpcMessage,
  type MCPConnectResult,
  type JsonRpcNotification,
  type JsonRpcRequest,
  type JsonRpcResponse,
  type MCPClientInfo,
  type MCPClientOptions,
  type MCPConnectionState,
  type MCPInitializeResult,
  type MCPReconnectOptions,
  type MCPRegistryServerOptions,
  type MCPServerConfig,
  type MCPSseServerConfig,
  type MCPStdioServerConfig,
  type MCPToolCallResult,
  type MCPToolConfig,
  type MCPToolContentBlock,
  type MCPToolDefinition,
  type MCPToolProviderOptions,
  type MCPToolsListResult,
  type MCPTransport,
  type SseEvent,
  type SseMCPTransportOptions,
  type StdioMCPTransportOptions,
} from './mcp/index.js';
